### ISSUE TITLE
Last online not visible on profiles

### ISSUE THREAD

**Issue by robinharms** [VoteIT/voteit.whosonline#3]
From @pillrin : I can't get VoteIT running locally so I can not verify this but on mote.voteit.se the profiles does not show last online times any more.

**Comment by robinharms** [comment]
@pillrin do you mean the popups within meetings? For profile pages it seems to work as expected for me.

**Comment by andershultman** [comment]
The popup when clicking a user in "who is online" used to show when that user was online. It does not any more.
